
# CF4 catalog selection: "cf4" or "cf4_velocities"
cf4_catalog_type: "cf4"

# Output folder selection: "default" or "temp"
output_folder_type: "default"

# Temporary folder name (only used if output_folder_type is "temp", will be inside output/)
temp_folder_name: "temp_bulkflow"

# Output file name (without folder path)
output_file_name: "bulkflow_cut_1400_to_1500.h5"

bulkflow:
  masks: "full"            # "full", "cf4", "uniform", or "all"
  max_radius: 250.0          # h^-1 Mpc
  min_radius: 50.0           # h^-1 Mpc
  radii_step: 5.0           # h^-1 Mpc
  error_fraction: 0.2        # 20%
  sigma_star: 250.0          # km/s
  sigma_min: 50.0            # km/s
  calculation_method: "chi2"  # "chi2" or "mean"
  cf4_match_radius: 5.0      # h^-1 Mpc for CF4 masking
  cf4_match_max_doublings: 5
  uniform_radius: 250.0      # h^-1 Mpc for uniform mask selection

origin_configs:
  local_overdensity_radius: 3.0    # h^-1 Mpc
  local_overdensity_upper_cut: 0.5
  local_overdensity_lower_cut: 0.4
  apply_overdensity_cut: false
  apply_mass_selection: false
  selection_mass_min: 1e14
  selection_mass_max: 1e16
  local_bulkflow_radius: 3.0     # h^-1 Mpc
  local_bulkflow_upper_cut: 1500.0  # km/s
  local_bulkflow_lower_cut: 1400.0    # km/s
  use_virgo_criteria: true
  number_of_origins: 1000
  mass_cut: 1e14                # h^-1 Msun
  mass_cut_bool: false        # if true, apply mass cut to the entire catalog
  select_lowest_delta: false  # if true, select points with lowest |delta|
  select_random: true      # if true, select random points from candidates after cuts

postprocessing:
  enabled: false
  build_comparison_plots: false
